---
title: "Lab 01 - Hello R"
author: "wejdan Abdulrhman Al-Harthy" 
date: "7/2/2021"
output: html_document
---

University ID: 2201001406

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Lab Exercise

(The concept from the data, which is that there are 13 rows in which there is an x axis with specified values, and there is also a y with specific values)

answer task3
In the previous figure, I have the shape of a dinosaur and it has a correlation coefficient of -0,0645, and now I have the shape of a star and it has a correlation coefficient of -0,0630 when comparing the two shapes. The dinosaur has a larger correlation coefficient and the star has a lower correlation coefficient

star_data <- datasaurus_dozen %>%
 filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
geom_point()
star_data %>%
 summarize(r = cor(x, y))

answer task4
When comparing the shape of the dino and the circle, the special correlation coefficient for the dino is -0.0645, the correlation coefficient for the circuit is -0.0683, so the circuit has a larger correlation coefficient, and the dino has a lower correlation coefficient

circle_data <- datasaurus_dozen %>%
 filter(dataset == "dino")
 ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
geom_point()
circle_data %>%
 summarize(r = cor(x, y))
